services:
  postgres_db:
    build:
      context: .
      dockerfile: ./Dockerfile.yaml
    image: "postgres-db"
    container_name: ${PG_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}
    volumes:
       - db_postgres:/data/postgres-db
    ports:
      - "5432:5432"
    restart: unless-stopped
volumes:
    db_postgres: