version: "3"

services:
  mongodb:
    image: mongo:4.4.9
    container_name: mongodb
    command: [mongod, --auth]
    ports:
      - 27927:27017
    environment:
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
        MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - ./mongo_data/mongod.conf:/etc/mongod.conf
      - ./mongo_data/data/db:/data/db
      - ./mongo_data/data/configdb:/data/configdb
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    entrypoint: ["docker-entrypoint.sh"]

volumes:
  mongo_data: